# Generated by Django 5.2.5 on 2025-12-24 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_quizer_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizer',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.option', unique=True),
        ),
    ]
