# Generated by Django 5.2.5 on 2026-01-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_quizer_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizer',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.option'),
        ),
    ]
