# Generated by Django 5.2.5 on 2026-01-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_quizer_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='playerRecord',
        ),
    ]
